### ISSUE TITLE
Request for an "Import Machine" feature

### ISSUE THREAD

**Issue by JayNaire** [statelyai/editor-feedback#86] opened 2022-04-18 22:34 UTC
May I request consideration of a "machine definition import" or c&p feature for the editor?

I have several old, hand crafted machines which need developing.
I currently cut and paste into viz which is great but will not allow visual editing.

Recreating these old machines in the editor from scratch is quite an effort (even though it sometimes reveals better ways of doing things).

Thanks for a terrific tool.

**Comment by mattpocock** [comment] 2022-04-19 08:13
Thanks for the lovely feedback! Closing as a duplicate of #12

**Closed by mattpocock** 2022-04-19 08:13 UTC
