### ISSUE TITLE
clicking 'give feedback' within the vscode extension makes the tab turn blank

### ISSUE THREAD

**Issue by trafnar** [statelyai/editor-feedback#62] opened 2022-03-21 05:32 UTC
using the xstate editor vscode extension, if you click the blue question mark, then 'give feedback' the vscode editor area turns blank, I assume because its trying to navigate to a URL within the tab.

Pressing this:
<img width="784" alt="image" src="https://user-images.githubusercontent.com/6732/159209637-fad91109-0b88-4d2c-97e9-253e5ddf31fd.png">

Results in this:
<img width="784" alt="image" src="https://user-images.githubusercontent.com/6732/159209654-ef0abc37-eb3b-4ef1-bad5-8cbc438296e6.png">

**Comment by mattpocock** [comment] 2022-03-21 09:04
Duplicate of #30

**Closed by mattpocock** 2022-03-21 09:04 UTC
