### ISSUE TITLE
Visualizer/Inspector can't find typescript machine if file contains `import { type x } from ".."`

### ISSUE THREAD

**Issue by mittinatten** [statelyai/editor-feedback#89] opened 2022-04-22 12:45 UTC
The following  machine can't be found by the VS code extension:

```ts
import { type x } from "...";

const machine = createMachine({
  states: {}
})
```

but the following works:
```ts
import type { x } from "...";

const machine = createMachine({
  states: {}
})
```

**Comment by Andarist** [comment] 2022-04-22 13:02
Duplicate of https://github.com/statelyai/xstate-tools/issues/137

**Closed by Andarist** 2022-04-22 13:02 UTC
