### ISSUE TITLE
Node popup menu doesn't pin location when scrolling with mousewheel

### ISSUE THREAD

**Issue by tivac** [statelyai/editor-feedback#10] opened 2022-01-24 19:19 UTC
https://user-images.githubusercontent.com/49545/150849379-5ea07dbf-91c9-4fb2-beed-007b75919b85.mp4

**To Reproduce:**

1. Select a node so the popup menu shows
2. Scroll the page with the mousewheel

**Expected result**

- Popup menu stays pinned to the node as the page scrolls

**Actual Result**

- Popup menu keeps its position on screen and runs away from its node

**Comment by mattpocock** [comment] 2022-01-24 19:34
Closing as a duplicate of #8, we're keen on fixing this

**Closed by mattpocock** 2022-01-24 19:34 UTC
